In [4]:
import pandas as pd 
import numpy as np


### Ejercicio 1

Dado un string, verificar si dicha variable es un palíndromo

In [5]:
def palindromo(palabra):
    return palabra==palabra[::-1]

palindromo('anana')

True

### Ejercicio 2
Dado un string que representa una frase, encontrar la palabra más larga en el string:
* Sin usar dictionary
* Usando dictionary

In [6]:
s = 'Hoy es el parcial de Computacion Cientifica Actuarial'

#### Sin dictionary

In [7]:
def palabra_mas_larga_sin_dict (frase):
    frase_list = frase.split()
    frase_largo = []
    for i in frase_list:
        frase_largo.append(len(i))
    posicion = frase_largo.index(max(frase_largo))    
    return frase_list[posicion]
palabra_mas_larga_sin_dict(s)     


'Computacion'

#### Con Dictionary

In [8]:
def palabra_mas_larga_con_dict (frase):
    dicionario = {len(i):i for i in frase.split()}
    valor_maximo = max(dicionario)
    respuesta = dicionario.get(valor_maximo)
    return respuesta
    
palabra_mas_larga_con_dict(s)

'Computacion'

### Ejercicio 3
Dada una lista de números, encontrar la suma de todos los elementos pares.

In [9]:
l = [1,2,3,4,5,6]
def suma_elementos_pares(lista):
    numeros = []
    for i in lista:
        if i%2 == 0:
            numeros.append(i)
    return sum(numeros)
suma_elementos_pares(l)

12

### Ejercicio 4

Dada una lista de nombres, agregar el prefijo “Sr.” a cada nombre terminado en ‘o’ y “Sra.” a cada
nombre terminado en ‘a’. Crear una nueva lista con tales nombres dentro del loop anterior.


In [10]:
nombres = ['Mariano', 'Juana', 'Santino', 'Juan', 'Clara']
def prefijos(lista):
    for i in lista:
        if  i[len(i)-1] == 'o':
            lista[lista.index(i)] = 'Sr '+i
        elif i[len(i)-1] == 'a':
            lista[lista.index(i)] = 'Sra '+i
    return lista
nueva_lista = prefijos(nombres)

nueva_lista       

['Sr Mariano', 'Sra Juana', 'Sr Santino', 'Juan', 'Sra Clara']

#### Ejercicio 5
Dados dos conjuntos (sets), encontrar los elementos comunes entre ellos. Encontrar los elementos
que están en uno de los conjuntos pero no en el otro.

In [11]:
s1= {1,2,3,4}
s2 = {1,3,5,8}
iguales = s1&s2
diferentes = s1^s2
print(iguales, diferentes)

{1, 3} {2, 4, 5, 8}


### Ejercicio 6
Genere una secuencia que imprima el siguiente resultado:
*  1
*  1 2
*  1 2 3
*  . . . . . .
*  1 2 3 4 5 6 7 8 9 10


In [12]:
def secuencia():
    for i in range(2,12):
        impt = list(range(1,i))
        for j in impt:    
            print(j, end=" ")
        print()
secuencia()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 
1 2 3 4 5 6 
1 2 3 4 5 6 7 
1 2 3 4 5 6 7 8 
1 2 3 4 5 6 7 8 9 
1 2 3 4 5 6 7 8 9 10 


#### Ejercicio 7
Genere una lista con los vehículos que pesan menos de 2000 kgs.Genere una lista con los vehículos que pesan menos de 2000 kgs.

In [13]:
dic = {"Auto": 1500, "SUV": 2000, "Pickup": 2500,
"Minivan": 1600,"Camioneta": 2400, "Camion": 13600,
"Bici": 7, "Moto": 110}

In [14]:
Nuevo_dic = {i:j for i,j in dic.items() if dic[i]<2000}
Nuevo_dic

{'Auto': 1500, 'Minivan': 1600, 'Bici': 7, 'Moto': 110}

#### Ejercicio 8
Dado un diccionario, generar un nuevo diccionario en el que las keys del primero sean los values del
segundo y viceversa con los values.

In [15]:
d = {
'key_1': 1,
'key_2': 2,
'key_3': 3,
'key_4': 4,
}

In [16]:
d_inverso = {j:i for i,j in d.items()}
d_inverso

{1: 'key_1', 2: 'key_2', 3: 'key_3', 4: 'key_4'}

#### Ejercicio 9 
Dado el siguiente np.array, se pide:
1. hallar el número máximo y mínimo del array.
2. hallar el número máximo y mínimo de cada columna y de cada fila.
3. reemplazar los valores mayores a 50 por 100

In [23]:
a = np.array([[4,12,9,24],
            [40,102,1,70],
            [34,6,2, 97]])



In [24]:
numero_maximo = a.max()
numero_minimo = a.min()
print('1- ',numero_maximo, numero_minimo)
fil_1 = a[0]
fil_2 = a[1]
fil_3 = a[2]

print('2-filas ',fil_1.max(),fil_2.max(),fil_3.max())
col_1 = a[:,0]
col_2 = a[:,1]
col_3 = a[:,2]
col_4 = a[:,3]
print('2-columnas ',col_1.max(),col_2.max(),col_3.max(), col_4.max())

b = np.where(a >50, 100, a)
print('3-', '\n',b)

1-  102 1
2-filas  24 102 97
2-columnas  40 102 9 97
3- 
 [[  4  12   9  24]
 [ 40 100   1 100]
 [ 34   6   2 100]]


#### Ejercicio 10
Dadas las siguientes matrices, genere una función que multiplique matrices, contemplando la necesidad de transponer cuando sea necesario, o que realice el producto ”element wise” cuando no haya
simetría ni siquiera post-transponerla. Verifique el resultado con las matrices A, B y C.

In [25]:
A = np.array([[5, 9, 3],
            [4, 1, 7]])
B = np.array([[8, 3, 2],
            [7, 5, 4]])
C = np.array([[8, 3, 2],
            [7, 5, 4],
            [4, 5, 3],
            [6, 2, 9]])



In [26]:
# No estoy seguro de que este bien
def mul_matrices(a,b):
    if a.shape[1] == b.shape[0]:
        return np.dot(a,b)
    elif a.shape[1] == b.shape[1] or a.shape[0] == b.shape[1]:
        return np.dot(a,b.T)
    else:
        print('element wise')
        return a*b
print(mul_matrices(A,B))
print(mul_matrices(A,C))
print(mul_matrices(B,C))
print(mul_matrices(C,B))
print(mul_matrices(C,A))
print(mul_matrices(B,A))



[[73 92]
 [49 61]]
[[73 92 74 75]
 [49 61 42 89]]
[[77 79 53 72]
 [79 90 65 88]]
[[77 79]
 [79 90]
 [53 65]
 [72 88]]
[[73 49]
 [92 61]
 [74 42]
 [75 89]]
[[73 49]
 [92 61]]


#### Ejercicio 11
Dado la siguiente lista, calcular la media móvil considerando 4 elementos para cada uno de sus
elementos.

In [27]:
lista_base = [25, 48, 74, 32, 96, 78, 44, 20, 10, 4, 87, 68, 55, 63, 54, 16, 22,8]
lista_media = [0.25, 0.25, 0.25, 0.25]

In [94]:
lista_base = [25, 48, 74, 32, 96, 78, 44, 20, 10, 4, 87, 68, 55, 63, 54, 16, 22,8]
def media_movil(l):
    l = np.array(l)
    i = 0
    pl = 3
    medias_moviles = []
    for i in range(0,len(l),4):
        if np.isnan(l[i:pl].mean()):
            break
        else:  
            medias_moviles.append(int(l[i:pl].mean()))
        pl=pl+3            

    return medias_moviles

media_movil(lista_base)


/tmp/ipykernel_4794/3670229696.py:8: RuntimeWarning: Mean of empty slice.
  if np.isnan(l[i:pl].mean()):


[49, 87, 10]

#### Ejercicio 12: 
Dada una secuencia de valores, determinar si existen valores que se repiten de forma consecutiva 3
o más veces.

In [95]:
seq = [1,2,2,3,3,3,4]

In [121]:
def contar_repetidos(seq):
    count = 0
    lista_repetidos = []
    l = set()
    for i in seq:
        if seq[i]==seq[i+1]:
            count +=1
        else:
            count = 1
        if count >= 3:
            l = set()
            l.add(i-1)

            # lista_repetidos.append(l)
    return list(l)

contar_repetidos(seq)    

[3]

#### Ejercicio 13:
Cree una función que dado un integer, una lista o un set, devuelva el valor de cada elemento elevado
a un valor k, que se deberá determinar como un parámetro de la función.


In [129]:
def potencia(a,b):
    if type(a) != int:
        lista = []    
        for i in a:
            lista.append(i**b)
        return lista
    else:
        return a**b


potencia(4,2)






16

#### Ejercicio 14: (puntaje: 10)
Dado el siguiente pd.DataFrame, se pide:
1. determinar la cantidad de nulos en el dataset y por columna.
2. completar los valores nulos con la media de columna.
3. crear una nueva columna tal que sea la suma de la ‘col1’ y la ‘col4’.
4. crear una nueva columna tal que sea el producto de la ‘col2’ y la ‘col3’, dividido por una
constante igual a 5.
5. determinar la cantidad de valores por columna que superan el valor de 8.
6. cambiar los nombres de todas las columnas por ‘columna_i’ en lugar del ‘col_i’.

In [184]:
rng = np.random.default_rng(999)
col1 = rng.choice(a = [1,2,3], size = 1000)
col2 = rng.choice(a = [25, 75, 150, np.nan], p = [0.5, 0.25, 0.15, 0.10], size =1000)
col3 = rng.exponential(5, size = 1000)
col4 = rng.uniform(low = 1, high = 10, size = 1000)
col5 = rng.choice(a = [1, 2, 3, 4, 5, 6 , 7, 8, 9, 10, np.nan], size = 1000)
cols = [col1, col2, col3, col4, col5]
X = pd.DataFrame(data = {'col1': col1,
'col2': col2,
'col3': col3,
'col4': col4,
'col5': col5,
})


In [185]:
print('Por columna',X.isna().sum())
print('En total',X.isna().sum().sum())

Por columna col1      0
col2    103
col3      0
col4      0
col5    104
dtype: int64
En total 207


In [189]:
X.head(20)

col1   col2       col3      col4  col5
0      3   25.0   4.649753  4.687258  10.0
1      3  150.0   0.375732  3.981954   9.0
2      1   25.0   8.109781  4.606976   8.0
3      1  150.0  12.984368  1.329778   1.0
4      1   75.0   1.704501  9.628617   8.0
5      3   75.0   1.619473  9.834628   8.0
6      1   25.0   0.605714  2.059097   7.0
7      3   25.0   1.910043  3.356397   5.0
8      1   25.0   2.194542  5.439999   8.0
9      1   75.0   5.558337  5.139334   6.0
10     1   25.0   7.587427  2.446766   8.0
11     3  150.0   0.247942  7.286054   8.0
12     1   25.0   7.452068  4.647055   6.0
13     1   75.0  11.859209  3.281007   NaN
14     3   25.0   0.179158  1.251387   8.0
15     2   25.0   6.701471  4.573648   3.0
16     2   75.0   2.137711  3.482047   7.0
17     3    NaN   7.272538  5.611713   NaN
18     2   75.0   1.992781  8.961456   2.0
19     1   25.0   5.218934  2.189458   3.0

In [211]:
X.fillna(X.mean(), inplace= True)

In [202]:
X['col1']

0      3
1      3
2      1
3      1
4      1
      ..
995    3
996    1
997    3
998    3
999    1
Name: col1, Length: 1000, dtype: int64

In [205]:
X['Col6']=X['col1']+X['col4']
X.head()

col1   col2       col3      col4  col5       Col6
0     3   25.0   4.649753  4.687258  10.0   7.687258
1     3  150.0   0.375732  3.981954   9.0   6.981954
2     1   25.0   8.109781  4.606976   8.0   5.606976
3     1  150.0  12.984368  1.329778   1.0   2.329778
4     1   75.0   1.704501  9.628617   8.0  10.628617

In [207]:
X['Col7']=(X['col2']*X['col3'])/5
X.head()

col1   col2       col3      col4  col5       Col6        Col7
0     3   25.0   4.649753  4.687258  10.0   7.687258   23.248764
1     3  150.0   0.375732  3.981954   9.0   6.981954   11.271948
2     1   25.0   8.109781  4.606976   8.0   5.606976   40.548904
3     1  150.0  12.984368  1.329778   1.0   2.329778  389.531054
4     1   75.0   1.704501  9.628617   8.0  10.628617   25.567508

In [216]:
X.where(X>8).count()

col1       0
col2    1000
col3     204
col4     210
col5     169
Col6     411
Col7     821
dtype: int64

In [217]:
X[X>8].count()

col1       0
col2    1000
col3     204
col4     210
col5     169
Col6     411
Col7     821
dtype: int64

In [231]:
nombre_columnas = []
for i in range(1,8):
    nombre_columnas.append(f'columna_{i}')
X.columns = nombre_columnas

In [232]:
X.head()

columna_1  columna_2  columna_3  columna_4  columna_5  columna_6  \
0          3       25.0   4.649753   4.687258       10.0   7.687258   
1          3      150.0   0.375732   3.981954        9.0   6.981954   
2          1       25.0   8.109781   4.606976        8.0   5.606976   
3          1      150.0  12.984368   1.329778        1.0   2.329778   
4          1       75.0   1.704501   9.628617        8.0  10.628617   

    columna_7  
0   23.248764  
1   11.271948  
2   40.548904  
3  389.531054  
4   25.567508

#### Ejercicio 15: 
Cree una función tal que dado un listado de palabras, devuelva todas las palabras que poseen un
palíndormo en la misma lista. Se deberá devolver una tuple que posea ambas palabras.

In [282]:
def palindrome_pairs(words):
    set1 = set()
    for i in range(0,(len(words))):
        for j in words:
            if i == words.index(j):
                continue
            elif words[i]==j[::-1]:
                set1.add(words[i])
                set1.add(j)
    return tuple(set1)
 

In [279]:
words = ["bat", "tab", "cat"]
palindrome_pairs(words)

('bat', 'tab')

In [280]:
def palindrome_pairs(words):
    set1 = set()
    lista=[]
    for i in range(0,len(words)):
        for j in words:
            if i == words.index(j):
                continue
            elif words[i]==j[::-1]:
                set1.add(words[i])
                set1.add(j)
    for i in range(0,len(set1),2):
        lista.append(tuple((list(set1))[i:i+2]))        
    return lista
 

In [281]:
words = ["abcd", "dcba", "lls", "s", "sll", "z"]
palindrome_pairs(words)[::1]

[('abcd', 'dcba'), ('lls', 'sll')]