# **Práctica 0-5**: Numpy

----

In [1]:
import numpy as np

#### Ejercicio 1:

Cree un vector nulo (es decir, un vector cuyos elementos sean 0) que posee las siguientes dimensiones:
1. (5,)
1. (2,3)
1. (4,2)

#### Ejercicio 2:

Cree un vector nulo (es decir, un vector cuyos elementos sean 0) que posea dimensión (10,). Reemplace el valor de la quinta posición por otro valor.

#### Ejercicio 3:

Cree un vector que posea todos los valores enteros desde el 6 hasta el 24, inclusive.

#### Ejercicio 4:

Cree una matriz de 3x3 que posea valores consecutivos del 0 al 8.

#### Ejercicio 5:

Dado los siguientes arrays, devuelva los índices que poseen valores distintos de 0.

```python
array_1 = np.array([2, 3, 0, 1, 2, 0, 4, 8, 0])

array_2 = np.array([2, 3, 0, 1], [2, 0, 4, 8])

array_3 = np.array([2, 3], [0, 1], [2, 0])

```

In [106]:
array_1 = np.array([2, 3, 0, 1, 2, 0, 4, 8, 0])
array_2 = np.array([[2, 3, 0, 1], [2, 0, 4, 8]])
array_3 = np.array([[2, 3], [0, 1], [2, 0]])
print(f'{np.where(array_1 != 0)} \n {np.where(array_2 != 0)} \n {np.where(array_3 != 0)}')





(array([0, 1, 3, 4, 6, 7]),) 
 (array([0, 0, 0, 1, 1, 1]), array([0, 1, 3, 0, 2, 3])) 
 (array([0, 0, 1, 2]), array([0, 1, 1, 0]))


#### Ejercicio 6:

Cree una matriz de 4x4 con valores aleatorios. Cambie sus dimensiones para que posea dos filas.

In [24]:
np.random.rand(16).reshape(4,4)

array([[0.04047139, 0.4305352 , 0.53873854, 0.20921385],
       [0.81942981, 0.22958576, 0.69417732, 0.5170683 ],
       [0.83601697, 0.15729309, 0.89670064, 0.51284777],
       [0.72636626, 0.95160256, 0.09491162, 0.44631365]])

#### Ejercicio 7:

Cree una matriz de valores aleatorios y calcule su media (global, por columna y por fila).

In [80]:
arr = np.random.rand(4)* 1000
arr2 = np.random.rand(16).reshape(4,4)*100

In [95]:

print(arr2)
print(arr2.mean())

for i in range(0,4):
    print(f'Fila {i} {arr2[i].mean()}')
    print(f'Columna {i} {arr2[:,i].mean()}')



[[36.68904531  2.51096039 43.23559724 57.77449015]
 [53.97231221 77.99251533 51.23312729 37.06995884]
 [31.58967454 78.29959753 85.85129166 48.33820301]
 [14.56935548 30.69782075 86.14389659 31.57875412]]
47.97166252866322
Fila 0 35.052523274498945
Columna 0 34.205096884731745
Fila 1 55.066978418518346
Columna 1 47.375223503473876
Fila 2 61.01969168573059
Columna 2 66.61597819621232
Fila 3 40.74745673590502
Columna 3 43.69035153023495


#### Ejercicio 8:

Cree una matriz diagonal cuyos valores sean [5, 8, 2, 4, 6], los demás valores son ceros. Luego, realice las operaciones necesarias para que los valores de la diagonal queden invertidos: la posición (0, 0) debe pasar a la posición (4, 0), y así sucesivamente.

In [124]:
arr = np.array([5,8,2,4,6])
identidad = np.identity(5)
a = arr*identidad
np.fliplr(a)

array([[0., 0., 0., 0., 5.],
       [0., 0., 0., 8., 0.],
       [0., 0., 2., 0., 0.],
       [0., 4., 0., 0., 0.],
       [6., 0., 0., 0., 0.]])

#### Ejercicio 9:

Dada una matriz, normalizar y/o estandarizar sus valores.

```python

[[3, 5, 34, 56, 12]
[45, 66, 7, 12, 33]
[34, 16, 27, 4, 9]]

```

*Hint*:
* **estandarizar**: $(X - X_{mean}) / X_{std}$
* **normalizar**: $(X - X_{min}) / (X_{max} - X_{min})$

In [145]:
m = np.array([
        [3, 5, 34, 56, 12],
        [45, 66, 7, 12, 33],
        [34, 16, 27, 4, 9]    
])

media = m.mean()
desvio = m.std()
maximo = m.max()
minimo = m.min()
estandar = (m-media)/desvio
normalizada = (m- minimo)/(maximo-minimo)
print(estandar, '\n'*2, normalizada)


[[-1.09853899 -0.99490324  0.50781519  1.64780849 -0.6321781 ]
 [ 1.07781184  2.16598725 -0.89126748 -0.6321781   0.45599732]
 [ 0.50781519 -0.42490659  0.14509006 -1.04672111 -0.78763173]] 

 [[0.         0.03174603 0.49206349 0.84126984 0.14285714]
 [0.66666667 1.         0.06349206 0.14285714 0.47619048]
 [0.49206349 0.20634921 0.38095238 0.01587302 0.0952381 ]]


#### Ejercicio 10:

1. Cree dos matrices aleatorias de tamaño 3x3 y realice la operación de adición entre ellas.
1. Genere una matriz aleatoria de tamaño 4x4 y reste un valor escalar (por ejemplo, 5) a cada elemento de la matriz.
1. Cree una matriz aleatoria de tamaño 2x3 y multiplique cada elemento por su correspondiente elemento en una matriz generada aleatoriamente del mismo tamaño.

#### Ejercicio 11:

1. Genere dos matrices aleatorias A y B de tamaño 4x3 y 3x5 respectivamente. Realice la multiplicación de matrices entre A y B.
1. Cree una matriz cuadrada aleatoria de tamaño 3x3 y calcule su inversa. Asegurar el manejo de casos donde la matriz no es invertible.
1. Genere una matriz cuadrada aleatoria de tamaño 5x5 y calcule su determinante utilizando NumPy.

#### Ejercicio 12:

1. Cree una matriz aleatoria de tamaño 4x4 y acceda al elemento en la primera fila y segunda columna.
1. Genere una matriz aleatoria de tamaño 3x3 y extraiga la primera fila de la matriz.
1. Cree una matriz aleatoria de tamaño 5x5 y seleccione solo los elementos mayores que 0.

#### Ejercicio 13:

1. Genere una matriz aleatoria de tamaño 6x6 y seleccione los elementos en las diagonales superior e inferior.
1. Cree una matriz aleatoria de tamaño 4x4 y extraiga una submatriz formada por las filas y columnas pares.
1. Genere una matriz aleatoria de tamaño 7x7 y seleccione un conjunto aleatorio de elementos de la matriz.

#### Ejercicio 14:

Dada una matriz y un escalar, determine cual es el valor presente en la matriz que es más cercano al valor del escalar, donde 'más cercano' refiere a aquel valor cuya distancia en valor absoluto es la menor.

```python
matriz=[5, 7, 3, 9], k=4
matriz=[7, 9, 12, 3], k=5
matriz=[2, -5, 5, 8], k=-3
matriz=[[2, -5], [3, 8]], k=0
```

#### Ejercicio 15:

Cree una matriz de valores al azar y realice las siguiente consignas:

1. Reemplace todos los elementos mayores a 10 por 100
1. Reemplace todos los elementos menores a 2 por -100
1. Devuelva los índices de los elementos que no son 100 ni -100

#### Ejercicio 16:

Dado el siguiente array  (`arr = np.arange(20)`) devolver:
1. todos los valores entre las posiciones 4 y 15
1. los elementos desde el índice 0, salteando un elemento entre cada uno
1. el reverso del array
1. el reverso del array, pero solo los primeros 4 valores de aquel

In [159]:
arr = np.arange(20)
print(arr[4:16])
print(arr[::2])
print(arr[::-1])
arr2 = arr[::-1]
print(arr2[0:4])

[ 4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  2  4  6  8 10 12 14 16 18]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[19 18 17 16]
